import imgOne from "../../images/1.jpg";
import imgTwo from "../../images/2.jpg";
import imgThree from "../../images/3.jpg";
import imgFour from "../../images/4.jpg";
import imgFive from "../../images/5.jpg";
import imgSix from "../../images/6.jpg";
import imgSeven from "../../images/7.jpg";
import imgEight from "../../images/8.jpg";
import userImage from "../../images/user.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHeart } from "@fortawesome/free-solid-svg-icons";

const loveIcon = <FontAwesomeIcon icon={faHeart} />;
const userDetails = [
  {
    id: 1,
    name: "Telephonic Robbit",
    cardImage: imgOne,
    userName: "madmaraca",
    userImage: userImage,
    endingIn: "58m : 34s ",
    endingInBg: "#262625",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Bid Now",
    borderColor: "#D0DF43",
  },
  {
    id: 2,
    name: "Telephonic Robbit",
    cardImage: imgTwo,
    userName: "madmaraca",
    endingInBg: "#262625",
    userImage: userImage,
    endingIn: "58m : 34s",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Buy now",
    borderColor: "#262626",
  },
  {
    id: 3,
    name: "Telephonic Robbit",
    cardImage: imgTwo,
    userName: "madmaraca",
    endingInBg: "#00000000",
    userImage: userImage,
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Create Offer",
    borderColor: "#262626",
  },
  {
    id: 4,
    name: "Telephonic Robbit",
    cardImage: imgThree,
    userName: "madmaraca",
    userImage: userImage,
    endingInBg: "#262625",
    endingIn: "58m : 34s",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "No offer accepted",
    borderColor: "#262626",
  },
  {
    id: 5,
    name: "Telephonic Robbit",
    cardImage: imgFour,
    userName: "madmaraca",
    userImage: userImage,
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    endingInBg: "#00000000",
    reactWhiteDot: "21",
    buttonText: "Bid Now",
    borderColor: "#262626",
  },
  {
    id: 6,
    name: "Telephonic Robbit",
    cardImage: imgFive,
    userName: "madmaraca",
    userImage: userImage,
    endingInBg: "##262625",
    endingIn: "58m : 34s",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Buy Now",
    borderColor: "#262626",
  },
  {
    id: 7,
    name: "Telephonic Robbit",
    cardImage: imgSix,
    userName: "madmaraca",
    userImage: userImage,
    endingInBg: "##262625",
    endingIn: "58m : 34s",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Bid Now",
    borderColor: "#262626",
  },
  {
    id: 8,
    name: "Telephonic Robbit",
    cardImage: imgSeven,
    userName: "madmaraca",
    userImage: userImage,
    endingInBg: "#00000000",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Bid Now",
    borderColor: "#2626263",
  },
  {
    id: 9,
    name: "Telephonic Robbit",
    cardImage: imgEight,
    userName: "madmaraca",
    userImage: userImage,
    endingInBg: "#262625",
    endingIn: "58m : 34s",
    icon: loveIcon,
    bid: "0.944 ETH 2 of 5",
    reactOnBid: "321",
    reactWhiteDot: "21",
    buttonText: "Buy Now",
    borderColor: "#D0DF43",
  },
];

export default userDetails;
